fs_control:
  parameters:
    deny_nested_rules: true
  paths:
    - ./path/to/your/project
  groups:
    Application: ~
    Domain: ~
    Infrastructure: ~
  bindings:
    $/Application: Application
    $/Domain: Domain
    $/Infrastructure: Infrastructure
  rule_attributes:
    _defaults:
      allowed_subdirectory_level: 2
      treat_exceed_subdirectory_level_as_fault: true
  rules:
    Entity:
      - Domain
    ParamConverter:
      - Infrastructure
    Command:
      - Application
