fs_control:
  paths:
    - ./example-fs/Shared
  exclude_paths:
    - ./example-fs/Shared/Infrastructure/ParamConverter/Check
  groups:
    Application: ~
    Domain: ~
    Infrastructure: ~
  bindings: # <path pattern> -> group
    $/Application: Application
    $/Domain: Domain
    $/Infrastructure: Infrastructure
  rule_attributes:
    _defaults:
      some_random_attribute: 'some_value'
    Entity:
      some_random_attribute: 'some_value'
  rules: # <directory name> -> [group, ...]
    Entity:
      - Domain
    ParamConverter:
      - Infrastructure
    Command:
      - Application
